// <auto-generated />
using JEM_id_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JEM_id_API.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231011104945_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JEM_id_API.Models.ArticleDto", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PlantHeight")
                        .HasColumnType("float");

                    b.Property<double>("PotSize")
                        .HasColumnType("float");

                    b.Property<int>("ProductGroup")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
